create table if not exists member (
        member_id bigint generated by default as identity,
        point integer not null,
        primary key (member_id)
);

create table if not exists menu (
        cnt integer not null,
        price integer not null,
        cafe_id bigint generated by default as identity,
        name varchar(255),
        primary key (cafe_id)
);

create table if not exists orders (
        order_id bigint generated by default as identity,
        is_pay_success boolean,
        price integer not null,
        created_at timestamp(6),
        member_id bigint,
        menu_id bigint,
        menu_name varchar(255),
        primary key (order_id)
);

create table if not exists payment (
        id bigint generated by default as identity,
        order_id bigint unique,
        primary key (id)
);

alter table if exists payment
       add constraint FKlouu98csyullos9k25tbpk4va
       foreign key (order_id)
       references orders